server:
  port: 8072

spring:
  application:
    name: product-service

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:4396
#ribbon要执行的负载均衡
product-service: # 调用的提供者的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.share.shareconter.configure.Nacosweight
